### ISSUE TITLE
web dav 有问题，上传后不在默认存储里面显示

### ISSUE THREAD

**Issue by LittleRey** [useblue/Cloudreve-Heroku#1]

**Comment by useblue** [comment]
刚刚测试了一下，WebDav功能一切正常，尝试使用Mysql版以解决此问题。默认版本会定时清除数据库，所以无法保存文件数据。

**Comment by ifloppy** [comment]
> 刚刚测试了一下，WebDav功能一切正常，尝试使用Mysql版以解决此问题。默认版本会定时清除数据库，所以无法保存文件数据。

请问这个数据库能否使用外部数据库？

**Comment by useblue** [comment]
x

> > 刚刚测试了一下，WebDav功能一切正常，尝试使用Mysql版以解决此问题。默认版本会定时清除数据库，所以无法保存文件数据。
> 
> 请问这个数据库能否使用外部数据库？

Mysql版使用的是Heroku提供的数据库。外部数据库应该是可以连接的，但是没有尝试过，连接问题可以自行尝试修改容器配置R2

**Comment by ifloppy** [comment]
> x
> 
> > > 刚刚测试了一下，WebDav功能一切正常，尝试使用Mysql版以解决此问题。默认版本会定时清除数据库，所以无法保存文件数据。
> > 
> > 
> > 请问这个数据库能否使用外部数据库？
> 
> Mysql版使用的是Heroku提供的数据库。外部数据库应该是可以连接的，但是没有尝试过，连接问题可以自行尝试修改容器配置R2

请问能否教一下我具体如何操作？我是萌新（

**Comment by useblue** [comment]
> > x
> > > > 刚刚测试了一下，WebDav功能一切正常，尝试使用Mysql版以解决此问题。默认版本会定时清除数据库，所以无法保存文件数据。
> > > 
> > > 
> > > 请问这个数据库能否使用外部数据库？
> > 
> > 
> > Mysql版使用的是Heroku提供的数据库。外部数据库应该是可以连接的，但是没有尝试过，连接问题可以自行尝试修改容器配置R2
> 
> 请问能否教一下我具体如何操作？我是萌新（

现在没有能供测试的数据库，你可以先尝试按照Mysql版的部署一次，随后按照模板修改为对应的数据库信息，优先使用ClearDB测试。
