### ISSUE TITLE
希望魔改一个地方

### ISSUE THREAD

**Issue by ifloppy** [useblue/Cloudreve-Heroku#2]
我想在cloudreve上挂载sharepoint，

这是我在loc上找到的教程：
Cloudreve挂载SharePoint教程
https://www.hostloc.com/thread-745894-1-1.html
(出处: 全球主机交流论坛)

**Comment by useblue** [comment]
如果有修改好的程序可以直接Fork仓库自行替换cloudreve(版本linux_amd64)文件进行部署,
